[project]
name = "mcp-proxy"
authors = [{ name = "Sergey Parfenyuk", email = "sergey.parfenyuk@gmail.com" }]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["mcp"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
